UNLABELED = 'unlabeled'
DISCRETE  = 'discrete'
CONTINUE  = 'continue'
ORDINAL   = 'ordinal'
LABEL     = 'label'

HeartDisease = {
    'blood_pressure_medication' : DISCRETE,
    'cholesterol_level': CONTINUE,
    'stroke_history' : DISCRETE,
    'systolic_pressure' : CONTINUE,
    'hypertension_history' : DISCRETE,
    'daily_cigarettes' : CONTINUE,
    'diastolic_pressure' : CONTINUE,
    'heart_rate' : CONTINUE,
    'smoking_status' : DISCRETE,
    'diabetes_history' : DISCRETE  ,
    'mass_index' : CONTINUE,
    'blood_sugar_level' : CONTINUE,
    'age' : CONTINUE,
    'education_level' : DISCRETE,
    'gender' : DISCRETE,
    'sleep_heart_rate' : CONTINUE,
    'ldl_cholesterol' : CONTINUE,
    'high_blood_sugar' : DISCRETE,
    'chd_risk' : LABEL
}

Pirvision = {
    'Timestamp' : UNLABELED,
    'Day Index' : DISCRETE,
    'Day' : UNLABELED,
    'Temp (F)' : CONTINUE,
    'Temp (C)' : CONTINUE,
    'OBS_1'  : CONTINUE,
    'OBS_2'  : CONTINUE,
    'OBS_3'  : CONTINUE,
    'OBS_4'  : CONTINUE,
    'OBS_5'  : CONTINUE,
    'OBS_6'  : CONTINUE,
    'OBS_7'  : CONTINUE,
    'OBS_8'  : CONTINUE,
    'OBS_9'  : CONTINUE,
    'OBS_10' : CONTINUE,
    'OBS_11' : CONTINUE,
    'OBS_12' : CONTINUE,
    'OBS_13' : CONTINUE,
    'OBS_14' : CONTINUE,
    'OBS_15' : CONTINUE,
    'OBS_16' : CONTINUE,
    'OBS_17' : CONTINUE,
    'OBS_18' : CONTINUE,
    'OBS_19' : CONTINUE,
    'OBS_20' : CONTINUE,
    'OBS_21' : CONTINUE,
    'OBS_22' : CONTINUE,
    'OBS_23' : CONTINUE,
    'OBS_24' : CONTINUE,
    'OBS_25' : CONTINUE,
    'OBS_26' : CONTINUE,
    'OBS_27' : CONTINUE,
    'OBS_28' : CONTINUE,
    'OBS_29' : CONTINUE,
    'OBS_30' : CONTINUE,
    'OBS_31' : CONTINUE,
    'OBS_32' : CONTINUE,
    'OBS_33' : CONTINUE,
    'OBS_34' : CONTINUE,
    'OBS_35' : CONTINUE,
    'OBS_36' : CONTINUE,
    'OBS_37' : CONTINUE,
    'OBS_38' : CONTINUE,
    'OBS_39' : CONTINUE,
    'OBS_40' : CONTINUE,
    'OBS_41' : CONTINUE,
    'OBS_42' : CONTINUE,
    'OBS_43' : CONTINUE,
    'OBS_44' : CONTINUE,
    'OBS_45' : CONTINUE,
    'OBS_46' : CONTINUE,
    'OBS_47' : CONTINUE,
    'OBS_48' : CONTINUE,
    'OBS_49' : CONTINUE,
    'OBS_50' : CONTINUE,
    'OBS_51' : CONTINUE,
    'OBS_52' : CONTINUE,
    'OBS_53' : CONTINUE,
    'OBS_54' : CONTINUE,
    'OBS_55' : CONTINUE,
    'OBS_56' : CONTINUE,
    'OBS_57' : CONTINUE,
    'Class'  : LABEL
}
